apiVersion: skaffold/v4beta11
kind: Config
metadata:
  name: kube-imds
build:
  artifacts:
    - image: rophy/kube-imds
      context: .
      docker:
        dockerfile: Dockerfile
        buildArgs:
          VERSION: '{{cmd "git" "describe" "--tags" "--always" "--dirty"}}'
    - image: rophy/kube-imds-e2e-client
      context: .
      docker:
        dockerfile: Dockerfile.e2e-client
      requires:
        - image: rophy/kube-imds
          alias: KUBE_IMDS
  local:
    push: false
    useBuildkit: true
  tagPolicy:
    gitCommit: {}
manifests:
  rawYaml:
    - deploy/kube-imds/*.yaml
    - deploy/e2e/*.yaml
deploy:
  kubectl: {}
