apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-worker-1
  namespace: kube-imds
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: vm-worker-unauthorized
  namespace: kube-imds
---
apiVersion: v1
kind: Pod
metadata:
  name: curl
  namespace: kube-imds
  labels:
    role: mapped-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-unauthorized
  namespace: kube-imds
  labels:
    role: unauthorized-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: curl-unknown
  namespace: kube-imds
  labels:
    role: unmapped-client
spec:
  containers:
    - name: curl
      image: curlimages/curl:latest
      command: ["sleep", "3600"]
---
apiVersion: v1
kind: Pod
metadata:
  name: client-test
  namespace: kube-imds
  labels:
    role: client-test
spec:
  containers:
    - name: client
      image: rophy/kube-imds-e2e-client
      command: ["sleep", "3600"]
